//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DojenApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kt_Subscriber
    {
        public int OID { get; set; }
        public Nullable<bool> Gesperrt { get; set; }
        public Nullable<bool> Passiv { get; set; }
        public Nullable<System.DateTime> PassivDatum { get; set; }
        public Nullable<int> PassivBenutzerOid { get; set; }
        public string DbConnectionString { get; set; }
        public Nullable<int> Angelegt { get; set; }
        public Nullable<System.DateTime> Erstellungsdatum { get; set; }
        public Nullable<int> Bearbeiter { get; set; }
        public Nullable<System.DateTime> Bearbeitungsdatum { get; set; }
        public string Id { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string Bounce { get; set; }
        public string ListId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Ip { get; set; }
        public string Unsubscription { get; set; }
        public string Unsubscription_Ip { get; set; }
        public Nullable<System.DateTime> Optin { get; set; }
        public string Optin_Ip { get; set; }
        public string Referrer { get; set; }
        public string Sms_Phone { get; set; }
        public string Sms_Status { get; set; }
        public string Sms_Bounce { get; set; }
        public Nullable<System.DateTime> Sms_Date { get; set; }
        public string Sms_Unsubscription { get; set; }
        public string Sms_Referrer { get; set; }
        public string FieldFirstName { get; set; }
        public string FieldLastName { get; set; }
        public string FieldCompanyName { get; set; }
        public string FieldStreet1 { get; set; }
        public string FieldStreet2 { get; set; }
        public string FieldCity { get; set; }
        public string FieldState { get; set; }
        public string FieldZip { get; set; }
        public string FieldCountry { get; set; }
        public string FieldPrivatePhone { get; set; }
        public string FieldMobilePhone { get; set; }
        public string FieldPhone { get; set; }
        public string FieldFax { get; set; }
        public string FieldWebsite { get; set; }
        public string FieldBirthday { get; set; }
        public string FieldLeadValue { get; set; }
        public string KlickKampagnenName { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    }
}
